//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCertification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Users = new HashSet<User>();
        }
    
        public string Task_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Project_ID { get; set; }
        public string Task1 { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
    
        public virtual Parent_task Parent_task { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
